---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: hazelcast
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: bridge
spec:
  finalizers:
    - kubernetes
